### ISSUE TITLE
SRS Review: Software constraints shouldn't match physical constraints

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#19]
Software constraints should describe what kinds of input you accept; traditionally these bound a value between a min and max. The constraint that the values be positive are already captured as physical constraints, so you don't need to repeat them.

**Comment by smiths** [comment]
I agree with @samm82.

**Comment by balacij** [comment]
![Screenshot from 2023-03-16 16-50-46](https://user-images.githubusercontent.com/1627302/225749769-96ad5d54-0fa7-41fd-8533-ed7550d328c1.png)


Merging @smiths's feedback with this, I am currently at this stage. Unfortunately, I'm not quite sure what other software constraints I should add. I added the maximums (but I'm not quite sure what a reasonable maximum is for any of them, so I'm taking guesses).

Is this okay?

**Comment by smiths** [comment]
@balacij guessing for the maximum values is fine.  As long as we only have to change them in one place, it is no big deal to keep them up to date.  :smile:

I did some googling and I think the following values would be meaningful.  They are still extreme, but not as extreme as your current values.  (We should actually find a way to capture the rationale for these values in the SRS document.  That's been an oversight on my part.)

Lmax = 60 m (It looks like 20 m is really long for a slender steel beam.  To get to 60 m seems to require a plate girder, which is actually a thick beam and outside the scope of your software.  A beam made out of titanium could span further than a steel beam, but people don't make beams out of titanium because of expense and the difficulty working with it.  There are other carbon composite fibre materials that have impressive properties, but I couldn't find any indication of people making really long beams out of them.  As a beam gets longer the deflection gets larger to the point where it is an issue.  Of course we might want to allow a larger Lmax just to see how large the deflection will get.  :smile:)

Emax = 2000E9 (The [highest known elastic modulus (Young's modulus) is diamond at 1210 GPa](https://www.sciencedirect.com/topics/immunology-and-microbiology/young-modulus#:~:text=The%20highest%20known%20Young's%20modulus,~%201210%20GPa%20%5B135%5D.), so 2000 GPa is already unrealistically high.  We might want to go with a value that is the same as diamond.  Nobody is going to be building a beam out of diamond.  :smile:)

Imax = 10 m^4 (If we assume a beam that has a rectangular cross-section has a height (h) of 5 m and a width(b) of 1 m, then I = 1/12*b*h^3 = 10.4 m^4.  No beam is going to have a height of 5 m, at least as far as I can imagine.)

**Comment by balacij** [comment]
Thank you very much @smiths! Those sound like very exciting maximum values. 82d22a43badf52e7560d61b42bed17fd4f703da7 should close this.
