### ISSUE TITLE
Acronyms in table that don't appear in the document

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#52]
The following acronyms appear in the table of acronyms, but not in the actual document: DC, DS, MG, MIS, and NB. PS also doesn't appear, but I'm guessing this will be added later.

My guess is that you populated the acronyms field with all terms that have acronyms, but Drasil doesn't currently work like this. Correcting this so that the table is populated with only the used acronyms is likely going to be part of Drasil generating content based on the existence of other content in the document.

**Comment by balacij** [comment]
I'd like to transport this ticket over to the main repository, what do you think? I feel like the printer should either (a) use the `acro` package to track acronyms used in a document, or (b) calculate the 'used acronyms' before printing the acronyms table, rather than just grabbing whatever was found in the ChunkDB. I _think_ this is also along the same lines of the `useddb` issue.

**Comment by smiths** [comment]
I think this issue is a good one for the main repo.  The table of acronyms should be populated automatically from the contents of the document.
