### ISSUE TITLE
Issues with Assumptions

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#59]
- [x] What is the tolerance of flatness? If it is irrelevant, I would just assume that the beam is perfectly flat. Otherwise, I think it would be worth it to add a symbolic parameter for tolerance.
![image](https://user-images.githubusercontent.com/35857611/229637647-95f25e6d-b491-443d-bd33-d37ead30f73d.png)
- [x] The use of the word "may" in beamLoadingPolynomial implies that it also may not; this may just be a nitpick about something that is personal preference, but I would use the word "can" to imply that it is able to be represented without the potential for ambiguity.
- [x] There is a period missing at the end of beamNoAxialLoading.
![image](https://user-images.githubusercontent.com/35857611/229637745-c198b49f-0806-46e9-a8bb-9f338c1dad91.png)

**Comment by balacij** [comment]
1. I don't think we can quantify this reasonably. I think the definition of “flat” should suffice here because it implies smooth, even, and tilt-free (along the axis we observe it).
2. Both “can” and “may” imply that the converse is possible too, but that's what I wanted. I only needed to know that one way to capture the loading is in a third-order polynomial. For example, if the user decided to have the third-power coefficient = 0, then it would be a second-order polynomial, but we can still call it a third-order polynomial. Alternatively if there were some other equivalent means of describing the same curve.
3. Thanks!
